name: Publish to npm on release
on:
  release:
    types:
    - published
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        NPM_PACKAGE_VERSION="$(echo $RELEASE_TAG_NAME | sed s/v//)"
        sed -i -e 's/"version": "0.0.0-dev"/"version": "'"$NPM_PACKAGE_VERSION"'"/' package.json
      env:
        RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org/'
    - run: yarn build
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
